# Generated by Django 3.1.6 on 2021-02-25 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date_of_examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_date', models.DateTimeField()),
                ('consultation_date', models.DateTimeField()),
                ('followup_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=64)),
                ('national_id_number', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('marital_status', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
                ('other', models.TextField(default='')),
                ('time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time', to='Clinic.date_of_examination')),
            ],
        ),
        migrations.CreateModel(
            name='Present_complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=200)),
                ('onset', models.CharField(max_length=200)),
                ('character', models.CharField(max_length=200)),
                ('radiation', models.CharField(max_length=200)),
                ('associations', models.CharField(max_length=300)),
                ('time_course', models.CharField(max_length=200)),
                ('exacerbation', models.CharField(max_length=200)),
                ('relieving_factors', models.CharField(max_length=200)),
                ('severity', models.CharField(max_length=200)),
                ('post_medical_history', models.TextField()),
                ('other_medical_problems', models.TextField()),
                ('drug_history', models.TextField()),
                ('family_history', models.TextField()),
                ('special_habits', models.CharField(max_length=300)),
                ('notes', models.TextField(default='')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='name', to='Clinic.id')),
            ],
        ),
        migrations.CreateModel(
            name='Past_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardiovascular_system', models.CharField(max_length=200)),
                ('respiratory', models.CharField(max_length=200)),
                ('gastrointestinal_tract', models.CharField(max_length=200)),
                ('neurology', models.CharField(max_length=200)),
                ('genitourinary', models.CharField(max_length=200)),
                ('renal', models.CharField(max_length=200)),
                ('musculoskeletal', models.CharField(max_length=200)),
                ('psychiatry', models.CharField(max_length=200)),
                ('complaint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint', to='Clinic.present_complaint')),
            ],
        ),
        migrations.CreateModel(
            name='Advise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation', models.CharField(max_length=400)),
                ('lab', models.CharField(max_length=100)),
                ('visual', models.CharField(max_length=100)),
                ('step_medication', models.CharField(max_length=400)),
                ('note', models.TextField()),
                ('history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hitory', to='Clinic.past_history')),
            ],
        ),
    ]
