# Generated by Django 3.1.6 on 2021-02-28 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0002_management'),
    ]

    operations = [
        migrations.DeleteModel(
            name='management',
        ),
    ]
